### ISSUE TITLE
Can't override the base template

### ISSUE THREAD

**Issue by workgator** [Starcross/django-starcross-gallery#14]
I am trying to override the base template (gallery_base.html) and followed the standard approach i.e 

- Set up the loaders in the template settings
- created a gallery/gallery_base.html in my project template. The effect is still not visible.

How can I override the template without customizing the source code?

**Comment by Starcross** [comment]
Hi there, this should be fine. I just checked myself and was able to override the base template in the way you described.

Can I check you are using a modified version of the gallery_base.html template, and not a brand new template? It will need block definitions to work correctly (header, content, etc).
