### ISSUE TITLE
NoReverseMatch at /admin/r/11/1/

### ISSUE THREAD

**Issue by claytonseraphin** [Starcross/django-starcross-gallery#3]
Hey guys, great job on this package, but i'm having this error by adding an image:
Reverse for 'album_detail' not found. 'album_detail' is not a valid view function or pattern name.
It's just a package, which means i don't think i have to copy and paste the whole template folder, thinking this work has been done in the background.
what might be the reason of that error ?
Thank you already.
![Screen Shot 2020-07-03 at 1 21 55 PM](https://user-images.githubusercontent.com/12686262/86488886-7bb8a600-bd30-11ea-9756-c77963b1dc45.png)

**Comment by demian18** [comment]
Hi, I have a counter question for you, how did you start the project at all? My whole problem comes down to the manage.py file, which simply does not exist

**Comment by Starcross** [comment]
The easiest way of making use of the package is to use the django-admin command to [start a new project](https://docs.djangoproject.com/en/3.0/ref/django-admin/#django-admin-startproject). You will then have a manage.py file to work with and can follow the readme to install the gallery package.

Closing this issue now.
